# Generated by Django 5.2.8 on 2025-12-01 14:50

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('capacity', models.CharField(max_length=100, verbose_name='capacity')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('duration', models.CharField(max_length=256, verbose_name='duration')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('full_name', models.CharField(max_length=256, verbose_name='full name')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('phone', models.CharField(max_length=256, verbose_name='phone')),
                ('date_joined', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='joined')),
                ('salary', models.PositiveIntegerField(verbose_name='Monthly Salary')),
                ('role', models.CharField(choices=[('Administrator', 'Administrator'), ('Accountant', 'Accountant'), ('Support', 'Support'), ('Receptionist', 'Receptionist')], max_length=256, verbose_name='status')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employee',
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='Informations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_admin', models.CharField(max_length=100, verbose_name='Admin')),
                ('tg_channel', models.CharField(max_length=100, verbose_name='Telegram Kanal')),
                ('instagram', models.CharField(max_length=100, verbose_name='Instagram')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone')),
                ('regions', models.CharField(choices=[('tashkent', 'Toshkent'), ('andijon', 'Andijon'), ('buxoro', 'Buxoro'), ('fargona', 'Farg‘ona'), ('jizzax', 'Jizzax'), ('namangan', 'Namangan'), ('navoiy', 'Navoiy'), ('qashqadaryo', 'Qashqadaryo'), ('samarqand', 'Samarqand'), ('sirdaryo', 'Sirdaryo'), ('surxondaryo', 'Surxondaryo'), ('xorazm', 'Xorazm')], max_length=100, verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Informations',
                'verbose_name_plural': 'Informations',
                'db_table': 'Informations',
            },
        ),
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(blank=True, choices=[('manager', 'Manager'), ('teacher', 'Teacher'), ('reception', 'Reception'), ('accountant', 'Accountant')], max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('price', models.IntegerField(verbose_name='price')),
                ('lesson_days', models.CharField(choices=[('mo we fri', 'Mon Wed Fri'), ('tu thu sa', 'Tu Thu Sat')], max_length=256, verbose_name='lesson days')),
                ('start_time', models.TimeField(verbose_name='start_time')),
                ('end_time', models.TimeField(verbose_name='end_time')),
                ('date_started', models.DateField(verbose_name='date')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Finished', 'Finished')], default='Active', max_length=256, verbose_name='status')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='common.course', verbose_name='course')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.classroom')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('full_name', models.CharField(max_length=256, verbose_name='full name')),
                ('birth_date', models.DateField(verbose_name='birth date')),
                ('phone', models.CharField(max_length=256, verbose_name='phone')),
                ('address', models.CharField(max_length=256, verbose_name='address')),
                ('status', models.CharField(choices=[('Request', 'Request'), ('Trial', 'Trial'), ('In group', 'In group')], max_length=256, verbose_name='status')),
                ('interested_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='common.course', verbose_name='interested course')),
            ],
            options={
                'verbose_name': 'lead',
                'verbose_name_plural': 'leads',
                'db_table': 'leads',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('full_name', models.CharField(max_length=256, verbose_name='full name')),
                ('birth_date', models.DateField(verbose_name='birth date')),
                ('phone', models.CharField(max_length=256, verbose_name='phone')),
                ('address', models.CharField(max_length=256, verbose_name='address')),
                ('balance', models.IntegerField(verbose_name='balance')),
                ('date_joined', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='joined')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Archive', 'Archive')], max_length=256, verbose_name='status')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='common.group', verbose_name='group')),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='amount')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='date')),
                ('debt', models.PositiveIntegerField(default=0, verbose_name='debt')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='common.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='common.student')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField()),
                ('grade', models.PositiveSmallIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.student')),
            ],
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=256, verbose_name='phone')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('full_name', models.CharField(max_length=256, verbose_name='full name')),
                ('birth_date', models.DateField(verbose_name='birth date')),
                ('phone', models.CharField(max_length=256, verbose_name='phone')),
                ('type', models.CharField(choices=[('Precent', 'Precent'), ('Group by', 'Group by')], max_length=100, verbose_name='type')),
                ('salary', models.CharField(help_text="Foiz: '20%' yoki Fix summa: '500000'", max_length=100, verbose_name='salary')),
                ('address', models.CharField(max_length=256, verbose_name='address')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Archive', 'Archive')], max_length=256, verbose_name='status')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='common.course', verbose_name='course')),
            ],
            options={
                'verbose_name': 'teacher',
                'verbose_name_plural': 'teachers',
                'db_table': 'teachers',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='common.teacher', verbose_name='teacher'),
        ),
        migrations.CreateModel(
            name='Wages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Administrator', 'Administrator'), ('Accountant', 'Accountant'), ('Support', 'Support'), ('Receptionist', 'Receptionist')], max_length=256)),
                ('method', models.CharField(choices=[('Bank Card', 'Bank Card'), ('Cash', 'Cash')], max_length=100, verbose_name='status')),
                ('amount', models.PositiveIntegerField()),
                ('date', models.DateField(default=datetime.date.today, verbose_name='date')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='common.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_role', models.CharField(choices=[('manager', 'Manager'), ('teacher', 'Teacher'), ('reception', 'Reception')], max_length=20, verbose_name='Qabul qiluvchi role')),
                ('message_type', models.CharField(blank=True, choices=[('attendance', 'Attendance (Davomat)'), ('baholash', 'Baholash'), ('payment', "Payment (To'lov)")], max_length=20, null=True, verbose_name='Xabar turi')),
                ('message', models.TextField(verbose_name='Xabar matni')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilganmi")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.course', verbose_name='Kurs')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Qabul qiluvchi (Profile)')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Yuboruvchi')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_583549_idx'), models.Index(fields=['status', 'created_at'], name='notificatio_status_dee16f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField()),
                ('is_present', models.BooleanField(default=False)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='common.group')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='common.student')),
            ],
            options={
                'ordering': ['-date_time'],
                'unique_together': {('student', 'date_time')},
            },
        ),
        migrations.CreateModel(
            name='StudentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_phone', models.CharField(help_text="Student modelidan avtomatik to'ldiriladi", max_length=20, verbose_name='Telefon raqami')),
                ('message_type', models.CharField(choices=[('attendance', 'Attendance (Davomat)'), ('payment', "Payment (To'lov)")], max_length=20, verbose_name='Xabar turi')),
                ('message', models.TextField(help_text="Type'ga qarab avtomatik generatsiya qilinadi", verbose_name='Xabar matni')),
                ('delivery_method', models.CharField(choices=[('telegram', 'Telegram'), ('sms', 'SMS')], max_length=20, verbose_name='Yuborish usuli')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Xatolik xabari')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='common.group', verbose_name='Guruh')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_student_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Yuboruvchi')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='common.student', verbose_name='Talaba')),
            ],
            options={
                'verbose_name': 'Student Notification',
                'verbose_name_plural': 'Student Notifications',
                'db_table': 'student_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'status'], name='student_not_student_47e112_idx'), models.Index(fields=['group', 'created_at'], name='student_not_group_i_949242_idx'), models.Index(fields=['status', 'delivery_method'], name='student_not_status_f25e1b_idx')],
            },
        ),
    ]
