# Generated by Django 5.2.8 on 2025-11-26 12:48

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('capacity', models.CharField(max_length=100, verbose_name='capacity')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('duration', models.CharField(max_length=256, verbose_name='duration')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('full_name', models.CharField(max_length=256, verbose_name='full name')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('phone', models.CharField(max_length=256, verbose_name='phone')),
                ('date_joined', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='joined')),
                ('salary', models.PositiveIntegerField(verbose_name='Monthly Salary')),
                ('role', models.CharField(choices=[('Administrator', 'Administrator'), ('Accountant', 'Accountant'), ('Support', 'Support'), ('Receptionist', 'Receptionist')], max_length=256, verbose_name='status')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employee',
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(blank=True, choices=[('manager', 'Manager'), ('teacher', 'Teacher'), ('reception', 'Reception'), ('accountant', 'Accountant')], max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('price', models.IntegerField(verbose_name='price')),
                ('lesson_days', models.CharField(choices=[('mo we fri', 'Mon Wed Fri'), ('tu thu sa', 'Tu Thu Sat')], max_length=256, verbose_name='lesson days')),
                ('start_time', models.TimeField(verbose_name='start_time')),
                ('end_time', models.TimeField(verbose_name='end_time')),
                ('date_started', models.DateField(verbose_name='date')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Finished', 'Finished')], default='Active', max_length=256, verbose_name='status')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='common.course', verbose_name='course')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.classroom')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('full_name', models.CharField(max_length=256, verbose_name='full name')),
                ('birth_date', models.DateField(verbose_name='birth date')),
                ('phone', models.CharField(max_length=256, verbose_name='phone')),
                ('address', models.CharField(max_length=256, verbose_name='address')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('TRIAL', 'TRIAL'), ('FROZEN', 'FROZEN')], max_length=256, verbose_name='status')),
                ('interested_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='common.course', verbose_name='interested course')),
            ],
            options={
                'verbose_name': 'lead',
                'verbose_name_plural': 'leads',
                'db_table': 'leads',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('full_name', models.CharField(max_length=256, verbose_name='full name')),
                ('birth_date', models.DateField(verbose_name='birth date')),
                ('phone', models.CharField(max_length=256, verbose_name='phone')),
                ('address', models.CharField(max_length=256, verbose_name='address')),
                ('balance', models.IntegerField(verbose_name='balance')),
                ('date_joined', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='joined')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Archive', 'Archive')], max_length=256, verbose_name='status')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='common.group', verbose_name='group')),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='amount')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='date')),
                ('debt', models.PositiveIntegerField(default=0, verbose_name='debt')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='common.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='common.student')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField()),
                ('grade', models.PositiveSmallIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.student')),
            ],
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=256, verbose_name='phone')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('full_name', models.CharField(max_length=256, verbose_name='full name')),
                ('birth_date', models.DateField(verbose_name='birth date')),
                ('phone', models.CharField(max_length=256, verbose_name='phone')),
                ('type', models.CharField(choices=[('Precent', 'Precent'), ('Group by', 'Group by')], max_length=100, verbose_name='type')),
                ('salary', models.CharField(help_text="Foiz: '20%' yoki Fix summa: '500000'", max_length=100, verbose_name='salary')),
                ('address', models.CharField(max_length=256, verbose_name='address')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Archive', 'Archive')], max_length=256, verbose_name='status')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='common.course', verbose_name='course')),
            ],
            options={
                'verbose_name': 'teacher',
                'verbose_name_plural': 'teachers',
                'db_table': 'teachers',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='common.teacher', verbose_name='teacher'),
        ),
        migrations.CreateModel(
            name='Wages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Administrator', 'Administrator'), ('Accountant', 'Accountant'), ('Support', 'Support'), ('Receptionist', 'Receptionist')], max_length=256)),
                ('method', models.CharField(choices=[('Bank Card', 'Bank Card'), ('Cash', 'Cash')], max_length=100, verbose_name='status')),
                ('amount', models.PositiveIntegerField()),
                ('date', models.DateField(default=datetime.date.today, verbose_name='date')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='common.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField()),
                ('is_present', models.BooleanField(default=False)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='common.group')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='common.student')),
            ],
            options={
                'ordering': ['-date_time'],
                'unique_together': {('student', 'date_time')},
            },
        ),
    ]
