# Generated by Django 5.2.8 on 2025-11-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('Request', 'Request'), ('Trial', 'Trial'), ('In group', 'In group')], max_length=256, verbose_name='status'),
        ),
    ]
