# Generated by Django 5.2.8 on 2025-12-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informations',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='logos/', verbose_name='logos'),
        ),
    ]
