# Generated by Django 5.2.8 on 2025-12-02 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='date_joined',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='joined'),
        ),
    ]
