# Generated by Django 5.2.8 on 2025-12-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_lead_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('Accountant', 'Accountant'), ('Teacher', 'Teacher'), ('Receptionist', 'Receptionist')], max_length=256, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='wages',
            name='role',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('Accountant', 'Accountant'), ('Teacher', 'Teacher'), ('Receptionist', 'Receptionist')], max_length=256),
        ),
    ]
