# Generated by Django 5.2.8 on 2025-12-06 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_employee_role_alter_wages_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wages',
            options={'verbose_name': 'Wage', 'verbose_name_plural': 'Wages'},
        ),
        migrations.AddField(
            model_name='wages',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='common.teacher'),
        ),
        migrations.AlterField(
            model_name='wages',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='common.employee'),
        ),
        migrations.AlterModelTable(
            name='wages',
            table='Wages',
        ),
    ]
