# Generated by Django 5.2.8 on 2025-12-06 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_wages_options_wages_teacher_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wages',
            options={},
        ),
        migrations.RemoveField(
            model_name='wages',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('Accountant', 'Accountant'), ('Receptionist', 'Receptionist')], max_length=256, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='wages',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='common.employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wages',
            name='role',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('Accountant', 'Accountant'), ('Receptionist', 'Receptionist')], max_length=256),
        ),
        migrations.AlterModelTable(
            name='wages',
            table=None,
        ),
    ]
