# Generated by Django 5.2.8 on 2025-12-06 10:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_wages_options_remove_wages_teacher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text="So'mda", max_digits=15, verbose_name="To'lov miqdori")),
                ('type', models.CharField(choices=[('cash', 'Cash (Naqd)'), ('bank_card', 'Bank Card')], default='cash', max_length=20, verbose_name="To'lov turi")),
                ('date', models.DateField(default=datetime.date.today, verbose_name="To'lov sanasi")),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_salaries', to='common.course', verbose_name='Kurs')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='common.teacher', verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': 'Teacher Salary',
                'verbose_name_plural': 'Teacher Salaries',
                'db_table': 'teacher_salaries',
                'ordering': ['-date'],
            },
        ),
    ]
