# Generated by Django 5.2.8 on 2025-12-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_teachersalary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersalary',
            name='type',
            field=models.CharField(choices=[('Cash', 'Cash (Naqd)'), ('Bank Card', 'Bank Card')], default='cash', max_length=20, verbose_name="To'lov turi"),
        ),
    ]
