# Generated by Django 5.2.8 on 2025-12-07 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_teachersalary_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersalary',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_salaries', to='common.group', verbose_name='Guruh'),
        ),
    ]
