# Generated by Django 5.2.8 on 2025-12-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_teachersalary_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='is_present',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
