# Generated by Django 5.2.8 on 2025-12-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_alter_attendance_is_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='recipient_role',
            field=models.CharField(choices=[('manager', 'Manager'), ('teacher', 'Teacher'), ('reception', 'Reception'), ('accountant', 'Accountant')], max_length=20, verbose_name='Qabul qiluvchi role'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'group', 'date_time')},
        ),
        migrations.DeleteModel(
            name='StudentNotification',
        ),
    ]
