# Generated by Django 5.2.8 on 2025-12-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_alter_notification_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.CharField(default=1, max_length=100, verbose_name='price'),
            preserve_default=False,
        ),
    ]
